[project]
name = "python-template"
version = "0.1.0"
description = "A Flask application for the NB-Signup-Form"
authors = [
    { name = "Your Name", email = "you@example.com" }
]
requires-python = ">=3.11"

dependencies = [
    "Flask>=3.0.0",
    "gunicorn>=20.1.0"
]
